#!/bin/sh

sxhkd &
compton -b

/home/ryan/src/scripts/monset.zsh &
/home/ryan/src/scripts/init-polybar.sh & 

bspc monitor "DisplayPort-1" -d 1 2 3 4 5 6 7 8 9 0
bspc monitor "HDMI-A-2" -d      1 2 3 4 5 6 7 8 9 0


bspc config border_width         5
bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config active_border_color "#E84F4F"
bspc config normal_border_color "#4C566A"
bspc config focused_border_color "#5E81AC"
bspc config urgent_border_color "#FF0000"

bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^10' state=floating follow=off
bspc rule -a firefox desktop='^1' follow=off
bspc rule -a discord desktop='^5' follow=off

