#!/usr/bin/env zsh

pgrep -x sxhkd > /dev/null || sxhkd &



ws1=("Web" "_>"  "_>" "_>"  "Msg")
ws2=("_>" "_>" "Music" "Mail" "Prop")

if [ "$HOST" = "Southpark" ]; then
    bspc monitor "HDMI-A-2" -d $ws1
    bspc monitor "DisplayPort-1" -d $ws2
    xset -display :0.0 s off
    xset -display :0.0 s noblank
else
    bspc monitor -d $ws1 $ws2
fi

bspc config merge_overlapping_monitors true


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a brave desktop='^1' focus=on follow=on
bspc rule -a discord desktop='^5'
bspc rule -a slack desktop='^5'
bspc rule -a element desktop='^5'
bspc rule -a Emacs state=tiled follow=on
bspc rule -a emacsclient state=tiled follow=on
bspc rule -a emacs state=tiled follow=on
bspc rule -a Steam desktop='^10'
bspc rule -a Screenkey manage=off



(sleep 3s && /home/ryan/src/dotfiles/scripts//init-polybar.sh) &>/dev/null &


picom -b

